FROM grafana/grafana:7.1.4-ubuntu

COPY ./assets/defaults.ini /usr/share/grafana/conf/
COPY ./assets/datasource-plugin-solr /usr/share/grafana/plugins-bundled/datasource-plugin-solr
COPY ./assets/marcusolsson-dynamictext-panel /usr/share/grafana/plugins-bundled/marcusolsson-dynamictext-panel
COPY ./assets/ilgizar-candlestick-panel /usr/share/grafana/plugins-bundled/ilgizar-candlestick-panel
COPY ./assets/grafana-clock-panel /usr/share/grafana/plugins-bundled/grafana-clock-panel
COPY ./assets/Dalvany-dalvany-image-panel /usr/share/grafana/plugins-bundled/Dalvany-dalvany-image-panel
COPY ./assets/innius-grafana-video-panel /usr/share/grafana/plugins-bundled/innius-grafana-video-panel
COPY ./assets/cloudspout-button-panel /usr/share/grafana/plugins-bundled/cloudspout-button-panel
COPY ./assets/ryantxu-ajax-panel /usr/share/grafana/plugins-bundled/ryantxu-ajax-panel
COPY ./assets/marcusolsson-json-datasource /usr/share/grafana/plugins-bundled/marcusolsson-json-datasource
COPY ./assets/fifemon-graphql-datasource /usr/share/grafana/plugins-bundled/fifemon-graphql-datasource
